package project_euler;


/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
*/


public class question2 {
	
	
		public static int fibEven(){
	        //this will be for fib sequence starting at 2
	        
	        int term1 = 1;
	        int term2 = 2;
	        int temp;
	        int highVal = 4000000;
	        
	        int evenSum = 2;
	        
	        while(term2 <= highVal){
	            temp = term2;
	            term2 += term1;
	            term1 = temp;
	            
	            if(term2 % 2 == 0)
	                evenSum += term2;
	        }
	        
	        return evenSum;
	        
	    }
	    
	    public static void main(String[] args){
	     
	        int answer = fibEven();
	    
	        System.out.println("the answer is: " + answer);
	    }

}
